SELECT a.id AS idlokus,
    a.parent_id AS parent_ro,
    a.kdlokasisoutput,
    a.nmlokasisoutput,
    a.wilayah_id,
    a.target_0,
    a.target_1,
    a.target_2,
    a.target_3,
    a.alokasi_total AS alokasi_total_perlokus,
    b.idro,
    b.tahun,
    b.thang,
    b.kementerian_kode,
    b.suboutput_nama,
    b.alokasi_total,
    b.kdtema,
    b.sat,
    b.program_kode,
    b.output_kode,
    b.kegiatan_kode,
    b.suboutput_kode,
    b.output_nama,
    b.satuan_output,
    b.alokasi_totaloutput,
    b.lokasi,
    b.kegiatan_nama,
    b.nmunit,
    b.nmprogout,
    b.program_nama,
    b.unit_kerja_eselon1,
    b.kementerian_nama,
    b.kementerian_nama_alias,
    c.kode AS kode_lokus,
    c.level,
    c.provinsi_id,
    c.kabupaten_id,
    c.nama AS nama_lokus,
    c.provinsi AS provinsi_lokus,
    c.kabupaten AS kabupaten_lokus,
    c.kewenangan
   FROM ((renja.krisnarenja_t_lokasi_suboutput a
     LEFT JOIN renja.mv_krisna_renja b ON (((a.parent_id = b.idro) AND ((a.tahun)::integer = (b.thang)::integer))))
     LEFT JOIN renja.krisnarenja_ref_wilayah c ON (((a.wilayah_id = c.id) AND ((a.tahun)::text = (c.tahun)::text))))
  WHERE (b.kdtema ~~* '%008%'::text)