on:
  push:
    branches:
      - 'develop'

jobs:
    deploy_job:
      runs-on: ubuntu-latest
      name: build&deploy
      steps:
        # To use this repository's private action, you must check out the repository
        - name: Checkout
          uses: actions/checkout@v2
        - name: ssh pipelines
          uses: cross-the-world/ssh-scp-ssh-pipelines@latest
          with:
            host: ${{ secrets.DEPLOY_HOST }}
            user: ${{ secrets.DEPLOY_USER }}
            pass: ${{ secrets.DEPLOY_PASSWORD }}
            script: |      
                cd /var/www/html/api-dev-v3
                git pull                
                exit
